chat_model:
  'model': "gpt-4o-mini" #?
  'temperature': 0.75
  #'num_gpu': 1

# OpenAI model for embeddings
embedding_model:
  model_name: "text-embedding-3-small"

# Pinecone configuration
pinecone_index_name: "multimodal-rag-chatbot"

#vector_database:
#  chroma:


chat_session_path: './chat_session/'


credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: 'hashed_password_for_jsmith' # Use the Hasher to generate this
    rbriggs:
      email: rbriggs@example.com
      name: Rebecca Briggs
      password: 'hashed_password_for_rbriggs'

cookie:
  name: ads_chatbot_cookie
  key: "a_secret_signature_key" # Change this to something random
  expiry_days: 30