[theme]
# The base theme can be "light" or "dark"
base = "dark"

# Primary accent color for interactive elements
primaryColor = "#7792E3"

# Main background color
#backgroundColor = "#0E1117"

# Background color for sidebar and most containers
#secondaryBackgroundColor = "#262730"

# Text color
textColor = "#FAFAFA"

# Font family
font = "sans serif"